---
ENVIRONMENT:
  DOMAIN_ID:
    definition: "d-abcdefghijkl"
    type: "PLAINTEXT"
    help: "SageMaker Studio Domain ID"
  IMAGE_NAME:
    definition: "smstudio-gtc"
    type: "PLAINTEXT"
    help: |
      "Note the suffix (naming convention). 
      Should match the input for image_name at runtime."
  ACCOUNT_ID:
    definition: "12345678901234"
    type: "PLAINTEXT"
    help: "AWS Account ID"
  REGION:
    definition: "us-east-2"
    type: "PLAINTEXT"
    help: "AWS Region, should match the region where the SageMaker domain is located."
  IMAGE_CONFIG:
    definition: "config-gtc"
    type: "PLAINTEXT"
    help: |
      "Note the suffix (naming convention). 
      Should match the input for image_name at runtime."
